version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kuntaapi
      MYSQL_USER: kuntaapi
      MYSQL_PASSWORD: random
  elastic:
    image: elasticsearch:5
  kuntaapi:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
    db_data: {}