version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kuntaapi
      MYSQL_USER: kuntaapi
      MYSQL_PASSWORD: random
    networks:
      - kanet
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - kanet
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kuntaapi:
    volumes:
      - m2_data:/opt/jboss/.m2
    build: .
    restart: always
    depends_on:
      - db
      - elastic
    ports:
      - "8080:8080"
    networks:
      - kanet
volumes:
    m2_data:
      driver: local
    db_data:
      driver: local
    es_data:
      driver: local

networks:
  kanet: