#!/bin/bash

while [[ true ]];
do
  management=`netstat -o -n -a | grep 9990 | grep LISTEN`
  if [[ -n $management ]]
  then
    break
  else
    echo "Waiting for management console"
    sleep 50
  fi
done
$SNAP/bin/jboss-cli.sh --file=$SNAP/startup.cli --properties=/var/snap/restful-ptv-server/common/jboss-cli.properties
