all:

install:
	install -D -m755 wrapper $(DESTDIR)/bin/wrapper
	install -D -m755 standalone.xml $(DESTDIR)/standalone/configuration/standalone-ka.xml
	install -D -m755 jboss.properties $(DESTDIR)/jboss.properties