all:

install:
	install -D -m755 wrapper $(DESTDIR)/bin/wrapper
	install -D -m755 deploy $(DESTDIR)/bin/deploy
	install -D -m755 startup.cli $(DESTDIR)/startup.cli
	install -D -m755 jboss-domain.properties $(DESTDIR)/jboss-domain.properties