all:

install:
	install -D -m755 wrapper $(DESTDIR)/bin/wrapper
	install -D -m755 jboss-standalone.properties $(DESTDIR)/jboss-standalone.properties
	install -D -m755 jboss-domain.properties $(DESTDIR)/jboss-domain.properties