#!/bin/sh

set -e
set -x

export JBOSS_HOME="$SNAP"
export JBOSS_MODE=domain
export JBOSS_LOG_DIR="$SNAP_DATA/wildfly/$JBOSS_MODE/log/"
export JBOSS_CONFIG_DIR="$SNAP_DATA/wildfly/$JBOSS_MODE/configuration/"

mkdir -p $JBOSS_CONFIG_DIR 
cp -n $JBOSS_HOME/$JBOSS_MODE/configuration/* $JBOSS_CONFIG_DIR

$JBOSS_HOME/bin/$JBOSS_MODE.sh --properties=$JBOSS_HOME/jboss-$JBOSS_MODE.properties